### PR TITLE
Feature: Add Resizable Information Block with Hover-activated Size Changer Component

### PR DESCRIPTION
**Pull request by Alimjan2013**
- Introduced a new information block component with dynamic resizing capabilities.
- Users can adjust the block size using a hover-activated size changer component.

- **Enhancement Note**: Animation for the size change will be refined in a future version.

image
image

check in page: http://localhost:3000/blocks

### CODE REVIEW

**Comment by James-Leste** [comment]
Reviewing

**Comment by James-Leste** [comment]
Email confirmation and register doesn't seem to work on this branch. I will look into it

**Review by James-Leste — APPROVED** [review]
Nice! The feature works well. There is some problems still in the routing between login and register page. I will look into it next.

**Comment by Alimjan2013** [comment]
> @Alimjan2013 Email confirmation and register doesn't seem to work on this branch. I will look into it

this is another branch without UI improvements for login and signup merged

**Pull request merged**
