### PR TITLE
Signup ux enhancement

### PR DESCRIPTION
**Pull request by Alimjan2013**
when user sign up with email and password, need guide user to open email and press link,
in present, if user didn't open link from email box, login will not success and can't register with same email agian.

image
image

### CODE REVIEW

**Review by James-Leste — CHANGES_REQUESTED** [review]
Great job! I suggest to adding a option for users to close the notifications. Is it possible?
image

**Comment by Alimjan2013** [comment]
yesss it is posiable, i will add it next time version in this branch

**Comment by Alimjan2013** [comment]
image
new state: add close button, need review @James-Leste

**Review by James-Leste — COMMENTED** [review]
Any specific reasons to change the name of the attribute from `cancelButton` to `closeButton`?

**Comment by Alimjan2013** [comment]
> Any specific reasons to change the name of the attribute from `cancelButton` to `closeButton`?

because cancelButton didn't work, when i change style , but closeButton can work, this is base on their documentation

**Comment by James-Leste** [comment]
> > Any specific reasons to change the name of the attribute from `cancelButton` to `closeButton`?
> 
> because cancelButton didn't work, when i change style , but closeButton can work, this is base on their documentation

Got it. I will approve the change

**Review by James-Leste — APPROVED** [review]

**Pull request merged**
